import { getSystemSolarSchedule, isNighttime } from './solarCalculator.js';
import { themeStorage, surfaceStyleStorage, nightVariantStorage, type AppTheme, type SurfaceStyle } from './themeStorage.js';
export type ResolvedTheme='light'|'dark'|'oled';
function systemPrefersDark(){return typeof window!=='undefined'&&window.matchMedia?window.matchMedia('(prefers-color-scheme: dark)').matches:false;}
export async function resolveActiveTheme():Promise<ResolvedTheme>{const appTheme=await themeStorage.get();const nightVariant=await nightVariantStorage.get();switch(appTheme){case'light':return'light';case'dark':return'dark';case'oled':return'oled';case'schedule':{const schedule=getSystemSolarSchedule();return isNighttime(new Date(),schedule)?nightVariant:'light';}case'system':default:return systemPrefersDark()?nightVariant:'light';}}
export async function applyAppearance(root:HTMLElement=document.documentElement):Promise<{theme:ResolvedTheme;surfaceStyle:SurfaceStyle}>{const [theme,surfaceStyle]=await Promise.all([resolveActiveTheme(),surfaceStyleStorage.get()]);root.setAttribute('data-theme',theme);root.setAttribute('data-surface-style',surfaceStyle);return{theme,surfaceStyle};}
export async function setAppTheme(value:AppTheme){await themeStorage.set(value);return applyAppearance();}
export async function setSurfaceStyle(value:SurfaceStyle){await surfaceStyleStorage.set(value);return applyAppearance();}
export function watchAppearance(root:HTMLElement=document.documentElement):()=>void{const reapply=()=>applyAppearance(root);const unwatchTheme=themeStorage.watch(reapply);const unwatchSurface=surfaceStyleStorage.watch(reapply);const unwatchVariant=nightVariantStorage.watch(reapply);let mql:MediaQueryList|undefined;const mqlListener=()=>reapply();if(typeof window!=='undefined'&&window.matchMedia){mql=window.matchMedia('(prefers-color-scheme: dark)');mql.addEventListener('change',mqlListener);}const interval=setInterval(reapply,60000);return()=>{unwatchTheme();unwatchSurface();unwatchVariant();mql?.removeEventListener('change',mqlListener);clearInterval(interval);};}
