import { notFound } from 'next/navigation';

const content:Record<string,{eyebrow:string;title:string;intro:string;items:string[]}>={
 foundations:{eyebrow:'FOUNDATIONS',title:'Build from a shared visual language.',intro:'The fundamental rules that give every M3 Glass interface a consistent Material-inspired structure.',items:['Overview','Color','Typography','Shape','Elevation','Motion','Accessibility']},
 glass:{eyebrow:'GLASS',title:'Optical depth, made systematic.',intro:'A dedicated rendering language for frosted shells, recessed surfaces, liquid highlights and opaque readability layers.',items:['Overview','Principles','Glass surfaces','Blur','Transparency','Refraction','Borders','Highlights','Shadows','Layering','Performance']},
 components:{eyebrow:'COMPONENTS',title:'Composable building blocks.',intro:'Reusable primitives and React components built on the M3 Glass surface model.',items:['Overview','Button','Icon button','Card','Dialog','Surface','Navigation','Selection','Text input']},
 patterns:{eyebrow:'PATTERNS',title:'Put the system to work.',intro:'Reusable structures for applications that need hierarchy, navigation and clear interaction states.',items:['Overview','App shell','Dashboard','Authentication','Forms','Data tables','Settings','Empty states','Loading states']},
 develop:{eyebrow:'DEVELOP',title:'From tokens to production.',intro:'Install the packages, compose themes and integrate M3 Glass into React and Next.js applications.',items:['Getting started','Installation','React','Next.js','Theming','Tokens','SSR','Migration']}
};
export function generateStaticParams(){return Object.keys(content).map(section=>({section}))}
export default async function Section({params}:{params:Promise<{section:string}>}){const {section}=await params;const data=content[section];if(!data)notFound();return <main className="doc-layout"><aside><p>{data.eyebrow}</p>{data.items.map((item,i)=><a key={item} className={i===0?'active':''} href={`/${section}`}>{item}</a>)}</aside><article><p className="eyebrow">{data.eyebrow}</p><h1>{data.title}</h1><p className="intro">{data.intro}</p><div className="doc-preview m3-glass"><div className="preview-orb"/><div><h2>Designed as a system.</h2><p>Every section connects visual principles to reusable implementation.</p></div></div><h2>Explore</h2><div className="topic-list">{data.items.map((item,i)=><div key={item}><span>{String(i+1).padStart(2,'0')}</span>{item}<b>→</b></div>)}</div></article></main>}
